version: '3.8'
services:
  appasesorias:
    build: .
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - MONGO_URI_FILE=/run/secrets/mongo_uri
    secrets:
      - mongo_uri
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example

secrets:
  mongo_uri:
    external: true

volumes:
  mongo-data:
