version: '3'
services:
  clienteasesorias:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - MONGO_URI_FILE=/run/secrets/mongo_uri
    depends_on:
      - mongo
  mongo:
    image: mongo
    env_file:
      - .env
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
