version: '3.8'
services:
  cliente-service:
    build: .
    ports:
      - "3001:3000"
      - "3002:3000"
      - "3003:3000"
    environment:
      - MONGO_URI_FILE=/run/secrets/mongo_uri
    secrets:
      - mongo_uri
    deploy:
      replicas: 3
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - mongo

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  nginx:
    image: nginx
    ports:
      - "80:80"
    depends_on:
      - cliente-service
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

secrets:
  mongo_uri:
    external: true

volumes:
  mongo-data:
